name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pod install
      - name: Build and test
        run: set -o pipefail && xcodebuild clean build -workspace uPic.xcworkspace -scheme uPic -sdk macosx -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO | xcpretty -c
      - name: list all files
        run: brew install tree && tree
      - name: set dmg name
        run: echo "DMG_NAME=`echo uPic-$(echo ${{ github.ref }} | cut -d / -f 3).dmg`" >> $GITHUB_ENV
      - name: create dmg
        run: brew install create-dmg && create-dmg --volname "uPic" ${DMG_NAME} /Users/runner/Library/Developer/Xcode/DerivedData/uPic-crddiursnoincvfvonukawsqsukj/Build/Products/Release/uPic.app
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DMG_NAME }}
          path: ${{ env.DMG_NAME }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.DMG_NAME }}
